# Предметы киборга уборщика
- type: entity
  parent: AdvMopItem
  name: borg mop
  id: BorgMopItem
  description: Motorized mop that has a bigger reservoir and quickly replaces reagents inside with water. Automatic Clown Countermeasure not included.
  components:
    - type: Sprite
      sprite: Imperial/Roles/Synthetics/Janitorial/mop.rsi
      layers: 
      - state: base
    - type: SolutionRegeneration
      solution: absorbed
      generated:
        reagents:
          - ReagentId: Water
            Quantity: 5
    - type: SolutionPurge
      solution: absorbed
      preserve:
        - Water
      quantity: 20
    - type: SolutionContainerManager
      solutions:
        absorbed:
          maxVol: 200

- type: entity
  name: borg trash bag
  id: TrashBagBorg
  parent: TrashBag
  components:
  - type: Sprite
    sprite: Imperial/Roles/Synthetics/Janitorial/trashbag.rsi
    layers:
      - state: icon-0
        map: ["enum.StorageFillLayers.Fill"]
  - type: Storage
    quickInsert: true
    areaInsert: true
    storageOpenSound:
      collection: trashBagRustle
    storageInsertSound:
      collection: trashBagRustle
    whitelist:
      tags:
        - Cartridge
        - Trash

# Предметы медицинского борга
- type: entity
  name: borg hypospray
  parent: BaseItem
  description: A sterile injector for rapid administration of drugs to patients.
  id: HyposprayBorg
  components:
  - type: Sprite
    sprite: Objects/Specific/Medical/hypospray.rsi
    state: borghypo
  - type: Item
    sprite: Objects/Specific/Medical/hypospray.rsi
  - type: SolutionContainerManager
    solutions:
      hypospray:
        maxVol: 30
  - type: RefillableSolution
    solution: hypospray
  - type: ExaminableSolution
    solution: hypospray
  - type: Hypospray
    onlyAffectsMobs: false
  - type: UseDelay
    delay: 0.5
  - type: StaticPrice
    price: 750
  - type: BorgHypo
    Solutions:
      - reagents:
        - ReagentId: Bicaridine
          Quantity: 1
      - reagents:
        - ReagentId: Dermaline
          Quantity: 1
      - reagents:
        - ReagentId: Dexalin
          Quantity: 1
      - reagents:
        - ReagentId: Inaprovaline
          Quantity: 1
      - reagents:
        - ReagentId: Hyronalin
          Quantity: 1
      - reagents:
        - ReagentId: Dylovene
          Quantity: 1
  - type: SolutionRegeneration
    solution: hypospray
    generated:
      reagents:
        - ReagentId: Epinephrine
          Quantity: 1

- type: entity
  id: ChangeReagent
  name: action-name-change-reagent
  description: action-description-change-reagent
  abstract: true
  components:
  - type: InstantAction
    itemIconStyle: NoItem
    icon:
      sprite: Objects/Specific/Medical/hypospray.rsi
      state: borghypo
    event: !type:ChangeReagentAction
    useDelay: 1