- type: entity
  id: BorgChassisSecurity
  parent: BorgChassisSelectable
  name: security cyborg
  components:
  - type: BorgSwitchableType
    selectedBorgType: security


# Security borg
- type: borgType
  id: security

  # Description
  dummyPrototype: BorgChassisSecurity

  # Functional
  extraModuleCount: 3
  moduleWhitelist:
    tags:
    - BorgModuleGeneric
    - BorgModuleSecurityImperial

  defaultModules:
  - BorgModuleJawsSecurity
  - BorgModuleNonLethalSecurity

  addComponents:
  - type: ShowJobIcons
  - type: ShowMindShieldIcons
  - type: ShowCriminalRecordIcons
  - type: FlashImmunity

  radioChannels:
  - Security
  - Science

  # Visual
  inventoryTemplateId: borgTall
  spriteBodyState: security
  spriteHasMindState: security_e
  spriteNoMindState: security_e_r
  spriteToggleLightState: security_l

  # Pet
  petSuccessString: petting-success-security-cyborg
  petFailureString: petting-failure-security-cyborg

  # Sounds
  footstepCollection:
    collection: FootstepSecurityCyborg


- type: Tag
  id: BorgModuleSecurityImperial


- type: soundCollection
  id: FootstepSecurityCyborg
  files:
  - /Audio/Imperial/Synthetics/sound_misc_step_step_robo_1.ogg
  - /Audio/Imperial/Synthetics/sound_misc_step_step_robo_2.ogg
  - /Audio/Imperial/Synthetics/sound_misc_step_step_robo_3.ogg
